[LibOS] remove warning in regression/large_dir_read.c
remove the following warning.

> large_dir_read.c:56:24: error: %010lu directive writing between 10 and 20 bytes into a region of size 16 [-Werror=format-overflow=]
>          sprintf(name, "%010lu", i);